version: '3'
services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./react:/usr/src/app
    command: sh -c "yarn run start"
    ports:
      - "3000:3000"
    tty: true